// This is the ONLY file that changes when you clone this module.
// See SCHEMA-SPEC.md for the full reference — quick version below.
// Rough cut auto-generated by db-cli.js (rule-based column-name matching,
// no AI) — hand-tune sections/profileActions/groupedSelect below same as
// any other cloned module.

import { hiveRoutes } from "../../appConfigs/hiveRoutes";

export const PendingapprovalSchema = {
  entity: 'system_users',              // DB table name; also drives default role names
                                     // (view_systemusers / manage_systemusers) and apiBase
  label: 'Systemusers',                 // optional, defaults to entity capitalized
  apiBase: `${hiveRoutes.hiveBaseRoute}/api/assetguard/pendingapproval`,

  // Field keys shown as columns in list view, in display order.
  showInList: ['row_count', 'name', 'email', 'tel', 'company_name', 'regdate', 'account_status'],

  rowLinks: [
    { key: 'review_account', type:'action', label: 'Review account', icon: 'bolt', variant: 'outline-success' },

  ],

  profileActions: [
    { key: 'back', label: 'Back to list', form:true, icon: 'arrow-left', variant: 'outline-secondary', navigateTo: '/assetguard/pendingapproval/list' },
    { key: 'delete', label: 'Delete', icon: 'trash', variant: 'outline-danger', confirm: 'Are you sure you want to delete this systemuser?', editOnly: true },
    { key: 'view', label: 'View & Edit', icon: 'edit', variant: 'outline-danger', rowAction : false},
    //{ key: 'new', label: 'Create user account', icon: 'plus', variant: 'outline-primary', navigateTo: '/assetguard/systemusers/profile' },
    { key: 'review_account', type:'action', label: 'Review account', icon: 'bolt', variant: 'outline-success',  },
    //{ key: 'clone', label: 'Clone Record', icon: 'copy', variant: 'outline-secondary', editOnly: true },
    //{ key: 'filterByDate', label: 'Filter by date', icon: 'calendar', variant: 'outline-primary' },
  ],

  fieldGroups: [],

  sections: [
    { key: 'basic_information', label: 'Basic Information', columns: 3, fields: ['name', 'email', 'tel', 'account_status', 'regdate', 'user_no', 'user_pic'] },
    { key: 'other_details', label: 'Other Details', columns: 3, fields: ['user_gender', 'last_seen', 'user_role'] },
    { key: 'about_user', label: 'Notes', columns: 1, fields: ['about'] },
  ],


  fields: [
    // key: DB column name | label: shown on screen | type: drives input + SQL type
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', label: 'Record Id', type: 'text', system: true, editable: false },
    { key: 'name', label: 'Name', type: 'text', title: true, required: true, searchable: true },
    { key: 'email', label: 'Email', type: 'text', searchable: true },
    { key: 'tel', label: 'Tel', type: 'text', searchable: true },
    { key: 'company_name', label: 'Company', type: 'text', searchable: true },
    { key: 'regdate', label: 'Created on', type: 'datetime', editable: false , computed:true },
    { key: 'user_no', label: 'User No', type: 'text', searchable: true },
    { key: 'user_pic', label: 'Photo', type: 'image', imageClass: "useravatar_120" },
    { key: 'user_gender', label: 'User Gender', type: 'select', options: ['male', 'female'], searchable: true },
    { key: 'last_seen', label: 'Last Seen', type: 'text', editable: false, computed: true },
    { key: 'about', label: 'About', type: 'textarea', searchable: true },
    { key: 'regions', label: 'Regions', type: 'textarea' , computed: true , editable:false },
    { key: 'clusters', label: 'Clusters', type: 'textarea' , computed: true ,editable: false},
    { key: 'role_name', label: 'Role', type: 'text', title: true, searchable: true },
    
    { key: 'user_role', 
      label: 'User Role', 
      type: 'liveSearch', 
      colSpan: 4, 
      endpoint: '/api/assetguard/systemroles',
      labelKey: 'role_name',
      searchTable: 'system_roles',
      valueField: 'record_id',      // id column on system_roles
      displayField: 'role_name',  // label column on system_roles — what search results/defaultValue text actually render
    },
    { key: 'company_id', 
      label: 'Company', 
      type: 'liveSearch', 
      colSpan: 4, 
      endpoint: '/api/assetguard/companies',
      labelKey: 'company_label',
      searchTable: 'companies',
      valueField: 'company_id',      // id column on system_roles
      displayField: 'company_name',  // label column on system_roles — what search results/defaultValue text actually render
    },
    { key: 'account_status', label: 'Account Status', type: 'select', options: ['active', 'inactive'], title: true, required: true  },
    { key: 'company_label', label: 'Company', type: 'text', searchable: true },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },
    // more fields... see SCHEMA-SPEC.md for the full field option list
    // (searchable, editable, options, priority, db overrides)
  ],

  filters: [
    { key: 'all', label: 'All', query: {} },
    { key: 'review_account', type:'action', label: 'Review account', icon: 'bolt', variant: 'outline-success' },
  ],

  actions: [
    // { key: 'some_action', label: 'Do Something', appliesTo: { status: 'x' } },
    // "key" must match a function registered in lib/actionsRegistry.js
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    // "_staff_full_name_staff_id": {
    //   type: "join", table: "staff", link: "staff_id:record_id",
    //   select: { "_staff_full_name_staff_id": "full_name" }
    // },
  },

  // Optional: only needed if permission keys don't follow the
  // view_<entity> / manage_<entity> default.
  // roles: { view: 'view_systemusers', manage: 'manage_systemusers' },
};
