// This is the ONLY file that changes when you clone this module.
// See SCHEMA-SPEC.md for the full reference — quick version below.
// Rough cut auto-generated by db-cli.js (rule-based column-name matching,
// no AI) — hand-tune sections/profileActions/groupedSelect below same as
// any other cloned module.
//
// FRONTEND schema — full UI shape (showInList, profileActions, apiBase,
// rowLinks, customBlocks, sections, moduleRole, etc). The trimmed backend
// counterpart lives alongside this at the api/ path and only carries
// entity/fields/batchMutations/roles.

import { getApiRoutes } from '../AppRoutes/apiRoutesHandler';
import DeviceFormSections from './uiControl/DeviceFormDetails';
// Use default base root (/)
const apiRoutes = getApiRoutes();
const moduleApi = apiRoutes.devices.base;

export const DevicesSchema = {
  entity: 'device_list',              // DB table name; also drives default role names
                                     // (view_devices / manage_devices) and apiBase
  label: 'Devices',                 // optional, defaults to entity capitalized
  apiBase: moduleApi,

  //api endpint for importing data from csv
  importDataEndpoint : apiRoutes.devices.import,

  // Page-level UI gate — checked once, for the WHOLE grid AND the WHOLE
  // profile/form page, via mosyACTRLHasRole. No moduleRole set -> open to
  // anyone (same additive convention as every other role/flag in this
  // file). This is a different layer than the per-action `role` flag
  // inside individual moduleActions entries below: moduleRole controls
  // whether someone can reach the page at all; a per-action role controls
  // whether one specific button shows up once they're already in. Same
  // UI-only caveat as those: route.js needs the equivalent server-side
  // check for this to be real enforcement, not just hiding.
  moduleRole: 'view_devices',


  gridOptions : {
   checkBoxes : false,
   checkFunction : "gridCheckBoxAction"  
  },

  multiGridRows: [
    // {
    //   key: 'order_items',
    //   parentTable: 'gps_logs',
    //   title: 'Log summary',
    //   columns: [
    //     { key: 'speed', label: 'Speed' },
    //     { key: 'latitude', label: 'Lat' },
    //     { key: 'longitude', label: 'Long' , sum: true},
    //     { key: 'remark', label: 'Selling price' }
    //   ],
    //   viewMoreLink: '../gpslogs/list',
    //   filter: { order_id: '{record_id}' },
    // },
  ],

  rowLinks: [],

  // Actions available from the list view, form and grid in display order.
  //{ 
  // key: 'filter_by_client', -- name of the action 
  // label: 'Filter by account', -- button label 
  // icon: 'user', -- icon of the buttons
  // grid:true, -- show on grid or not, 
  // type: 'action', -- indicates action on form registry 
  // form: false, -- show on form or not, 
  // rowAction: false --show on row drop down or not
  // variant : 'outline-primary', -- button color  variant
  // navigateTo: '/supererpv5/revenueplan/profile', -- route to navigate to -  for link buttons only 
  // colorClass:"bg-success text-white", -- button color classname 
  // confirm: 'Are you sure you want to delete this revenueplan?', -- confirmation message for delete button
  // editOnly: true, -- show on edit only or not
  // role: 'manage_revenueplan' -- role required for this action
  //},

  profileActions: [
    { key: 'back', label: 'Back to list', icon: 'arrow-left', variant: 'outline-secondary', navigateTo: '/assetguard/devices/list', grid: false, form: true },
    { key: 'save', label: 'Save', icon: 'save', variant: 'primary', grid: false, form: true, rowAction: false },
    { key: 'delete', label: 'Delete', icon: 'trash', variant: 'outline-danger', confirm: 'Are you sure you want to delete this device?', editOnly: true, grid: false, form: true, rowAction: true, role: 'manage_devices' },
    { key: 'view', label: 'View more', icon: 'edit', rowAction: true },
    { key: 'new', label: 'New Device', icon: 'plus', variant: 'outline-primary', navigateTo: '/assetguard/devices/profile', grid: true, form: false, rowAction: false },
    { key: 'clone', label: 'Clone Record', icon: 'copy', variant: 'outline-secondary', editOnly: true, grid: false, form: true, rowAction: false, role: 'manage_devices' },
    //{ key: 'filterByDate', label: 'Filter by date', icon: 'calendar', variant: 'outline-primary', type: 'action', grid: true, form: false, rowAction: false },
  ],



  // customBlocks — the escape hatch for UI that doesn't fit the rigid
  // field-grid: a raw component, handed the SAME values/setValue/errors/
  // schema/isEditing/row context a real field gets. A block's `key` just
  // sits in a section's `fields` array exactly like a real field key —
  // wherever it appears there is where it renders. Empty by default;
  // uncomment and point at a real component when a field needs custom UI
  // (see SCHEMA-SPEC.md for the full pattern, e.g. companies/schema.js).
  customBlocks: [
    { key: 'other_details', component: DeviceFormSections, colSpan: 7 },
  ],

  fieldGroups: [],
  // Field keys shown as columns in list view, in display order.
  showInList: ['row_count', 'device_name', 'date_installed', 'serial_number', 'remark', 'registered_on', 'geofence', 'site_id'],

  //export columns these columns are used to generate upload csv template file
  exportColumns: ['device_name', 'date_installed', 'serial_number', 'remark', 'registered_on', 'geofence', 'site_id'],

  sections: [
    { key: 'site_details', label: 'Site', columns: 1, fields: ['site_id'] },
    { key: 'other_details', label: 'Other Details', columns: 1, fields: ['other_details'] },
  ],

  fields: [
    // key: DB column name | label: shown on screen | type: drives input + SQL type
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', label: 'Record Id', type: 'text', system: true, editable: false },
    { key: 'device_name', label: 'Device Name', type: 'text', title: true, required: true },
    { key: 'date_installed', label: 'Date Installed', type: 'datetime' },
    { key: 'serial_number', label: 'Serial Number', type: 'text' },
    { key: 'remark', label: 'Remark', type: 'textarea', colSpan: 3 },
    { key: 'registered_on', label: 'Registered On', type: 'datetime' },
    { key: 'geofence', label: 'Geofence', type: 'text' },
    { key: 'site_id', label: 'Site Id', type: 'text' },
    { key: 'site_name', label: 'Site Name', type: 'text', title: true },
    { key: 'low_battery_level', label: 'Low Battery Level', type: 'text' },
    { key: 'geofence_limit_distance', label: 'Geofence Limit Distance', type: 'text' },
    { key: 'device_location', label: 'Device Location', type: 'text' },
    { key: 'speed_alert_value', label: 'Speed Alert Value', type: 'text' },
    { key: 'device_type', label: 'Device Type', type: 'text' },
    { key: 'status', label: 'Status', type: 'groupedSelect', endpoint: '/api/assetguard/devices', groupByField: 'status' },
    { key: 'last_seen', label: 'Last Seen', type: 'datetime' },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },
    //  live search field sample 
    { key: 'site_id', label: 'Site name / id',
      type: 'liveSearch', colSpan: 6,
      endpoint: '/api/assetguard/sites',
      searchTable: 'sites',
      valueField: 'record_id',      // id column on system_modules
      displayField: 'site_name',  // label column on system_modules — what search results/defaultValue text actually render
      labelKey: 'site_name',  // cached label already joined onto THIS row (system_roles) — only used to seed defaultValue on load
    },
    // more fields... see SCHEMA-SPEC.md for the full field option list
    // (searchable, editable, options, priority, db overrides)
  ],

  filters: [
    { key: 'all', label: 'All', query: {} },
  ],

  actions: [
    // { key: 'some_action', label: 'Do Something', appliesTo: { status: 'x' } },
    // "key" must match a function registered in lib/actionsRegistry.js
  ],

// for button color classes  
// dyn-btn-accent-amber  { border-color: transparent; color: #b45309; }
// dyn-btn-accent-green  { border-color: transparent; color: #047857; }
// dyn-btn-accent-purple { border-color: transparent; color: #6d28d9; }
// dyn-btn-accent-pink   { border-color: transparent; color: #be185d; }
// dyn-btn-accent-red    { border-color: transparent; color: #b91c1c; }
// dyn-btn-accent-yellow { border-color: transparent; color: #a16207; }
// dyn-btn-accent-blue   { border-color: transparent; color: #1d4ed8; }
// dyn-btn-accent-teal   { border-color: transparent; color: #0f766e; }

  // Optional: only needed if permission keys don't follow the
  // view_<entity> / manage_<entity> default.
  // roles: { view: 'view_devices', manage: 'manage_devices' },
};
