// Auto-generated by db-cli.js — BACKEND schema (trimmed).
// This is the data-shape-only counterpart to the frontend schema.js at the
// matching app/ path. It intentionally does NOT include showInList,
// profileActions, apiBase, rowLinks, customBlocks, sections, moduleRole,
// filters, or actions — those are UI concerns and live in the frontend
// schema only. Field entries also omit `label` here (UI-only display
// text) even though the frontend fields carry it. Edit
// fields/batchMutations/roles here; edit everything else there. Keep the
// `fields` array in sync between the two by regenerating both together
// (this tool writes both from the same column read).

export const SitesSchema = {
  entity: 'sites',

  moduleRole: 'view_sites',

  fields: [
    // key: DB column name | type: drives SQL/validation (label omitted —
    // UI-only, lives in the frontend schema)
    { key: 'primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', type: 'text', system: true, editable: false },
    { key: 'site_name', type: 'text', title: true, required: true, searchable: true },
    { key: 'site_code', type: 'text', title: true, searchable: true },
    { key: 'country', type: 'groupedSelect', endpoint: '/api/assetguard/sites', groupByField: 'country', searchable: true },
    { key: 'city', type: 'text', searchable: true },
    { key: 'county', type: 'groupedSelect', endpoint: '/api/assetguard/sites', groupByField: 'county', searchable: true },
    { key: 'town', type: 'groupedSelect', endpoint: '/api/assetguard/sites', groupByField: 'town', searchable: true },
    { key: 'latitude', type: 'money' },
    { key: 'longitude', type: 'money' },
    { key: 'location_address', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'remark', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'created_on', type: 'datetime' },
    { key: 'manager', type: 'text', searchable: true },
    { key: 'manager_mobile', type: 'text', searchable: true },
    { key: 'manager_email', type: 'text', searchable: true },
    { key: 'vehicle_registration_number', type: 'text', searchable: true },
    { key: 'management_company', type: 'groupedSelect', endpoint: '/api/assetguard/sites', groupByField: 'management_company', searchable: true },
    { key: 'status', type: 'groupedSelect', endpoint: '/api/assetguard/sites', groupByField: 'status', searchable: true },
    { key: 'region', type: 'groupedSelect', endpoint: '/api/assetguard/sites', groupByField: 'region', searchable: true },
    { key: 'smpms_vendor', type: 'groupedSelect', endpoint: '/api/assetguard/sites', groupByField: 'smpms_vendor', searchable: true },
    { key: 'security_company', type: 'groupedSelect', endpoint: '/api/assetguard/sites', groupByField: 'security_company', searchable: true },
    { key: 'response_cluster', type: 'text', searchable: true },
    { key: 'additional_sms_recipients', type: 'textarea', searchable: true },
    { key: 'additional_email_recipients', type: 'textarea', searchable: true },
    { key: 'last_inspection_date', type: 'datetime' },
    { key: 'hive_site_id', type: 'text', searchable: true },
    { key: 'hive_site_name', type: 'text', title: true, searchable: true },
    { key: 'distribution_region', type: 'text', searchable: true },
    { key: 'coordinates', type: 'text', searchable: true },
    { key: 'noc_company', type: 'groupedSelect', endpoint: '/api/assetguard/sites', groupByField: 'noc_company', searchable: true },
    { key: 'row_count', type: 'number', computed: true, editable: false },
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    // "_staff_full_name_staff_id": {
    //   type: "join", table: "staff", link: "staff_id:record_id",
    //   select: { "_staff_full_name_staff_id": "full_name" }
    // },
  },

  roles: { view: 'view_sites', manage: 'manage_sites' },
};
