// This is the ONLY file that changes when you clone this module.
// See SCHEMA-SPEC.md for the full reference — quick version below.
// Rough cut auto-generated by db-cli.js (rule-based column-name matching,
// no AI) — hand-tune sections/profileActions/groupedSelect below same as
// any other cloned module.

import MainPurposePills from './uiControl/MainPurposePills'; // adjust path to match where this file actually sits relative to schema.js

export const CompaniesSchema = {
  entity: 'companies',              // DB table name; also drives default role names
                                     // (view_companies / manage_companies) and apiBase
  label: 'Companies',                 // optional, defaults to entity capitalized
  apiBase: '/api/assetguard/companies',

  // Page-level UI gate — checked once, for the WHOLE grid AND the WHOLE
  // profile/form page, via mosyACTRLHasRole. No moduleRole set -> open to
  // anyone (same additive convention as every other role/flag in this
  // file). This is a different layer than the per-action `role` flag
  // inside individual moduleActions entries below: moduleRole controls
  // whether someone can reach the page at all; a per-action role controls
  // whether one specific button shows up once they're already in. Same
  // UI-only caveat as those: route.js needs the equivalent server-side
  // check for this to be real enforcement, not just hiding.
  moduleRole: 'view_companies',

  // Field keys shown as columns in list view, in display order.
  showInList: ['row_count', 'company_logo','company_name', 'purposes', 'phone_number', 'email', 'address'],

  rowLinks: [],

  // moduleActions — one array, three possible places each entry can
  // render, spelled out explicitly on every entry (no implicit
  // defaults): CompaniesGrid.jsx, DynamicForm.jsx, and EntityRowOptions'
  // dropdown all read this SAME array, each filtering on its own flag.
  // Comment an entry out, or flip a flag to false, and it disappears
  // from that one place — no component edit needed.
  //   grid: true/false      -> grid toolbar (list page)
  //   form: true/false      -> profile/form toolbar ('save' is also the
  //                            primary submit button — DynamicForm picks
  //                            the submit button as whichever entry has
  //                            both form:true and key:'save')
  //   rowAction: true/false -> per-row dropdown in the grid (EntityRowOptions)
  //   editOnly: true        -> only shown once a record exists (form/rowAction contexts)
  //   role: 'role_name'     -> UI-ONLY gate, checked via mosyACTRLHasRole
  //                            (session roles from localStorage). Omit
  //                            entirely and the action is open to anyone —
  //                            this is additive, not a default-deny system.
  //                            NOTE: this does not by itself stop the
  //                            request server-side — route.js currently
  //                            gates every mutation behind one blanket
  //                            manage_<entity> role regardless of which
  //                            action triggered it. Real enforcement needs
  //                            the same per-action role checked there too.
  profileActions: [
    { key: 'back', label: 'Back to list', icon: 'arrow-left', variant: 'outline-secondary', navigateTo: '/assetguard/companies/list', grid: false, form: true },
    { key: 'save', label: 'Save', icon: 'save', variant: 'primary', grid: false, form: true, rowAction: false },
    { key: 'delete', label: 'Delete', icon: 'trash', variant: 'outline-danger', confirm: 'Are you sure you want to delete this record?', editOnly: true, grid: false, form: true, rowAction: true, role: 'manage_companies' },
    { key: 'view', label: 'View more', icon: 'edit', rowAction: true },
    { key: 'register_company', label: 'Register company', icon: 'plus', variant: 'outline-info', type: 'action', grid: true, form:false},
    
    //register company profile comp
    { key: 'register_company_profile', label: 'New company', icon: 'plus-circle', variant: 'outline-primary', navigateTo: './profile', form: true, rowAction: false },
    //{ key: 'new', label: 'Register company', icon: 'plus', variant: 'outline-primary', form: true, navigateTo:"./profile", rowAction: false },
    { key: 'clone', label: 'Clone Record', icon: 'copy', variant: 'outline-secondary', editOnly: true, grid: false, form: true, rowAction: false, role: 'manage_companies' },
    //{ key: 'filterByDate', label: 'Filter by date', icon: 'calendar', variant: 'outline-primary', type: 'action', grid: true, form: false, rowAction: false },
  ],

  //1110 /=
  // customBlocks — the escape hatch for UI that doesn't fit the rigid
  // field-grid: a raw component, handed the SAME values/setValue/errors/
  // schema/isEditing/row context a real field gets (row is the raw
  // fetched record, for anything not captured in values — null on a
  // new/create-mode record). Not a separate island — whatever key(s) it
  // calls setValue() on are just more form data as far as Save/Clone/
  // create/update are concerned.
  //
  // No anchor properties (after/before/position/etc) — a block's `key`
  // just sits in a section's `fields` array exactly like a real field
  // key. Wherever it appears is where it renders.
  //
  // colSpan is real Bootstrap col-md-N — always N out of 12, regardless
  // of section.columns (columns only sets the DEFAULT width for entries
  // that don't specify their own colSpan). Set it explicitly to put
  // fields side by side at whatever widths you want, e.g. email at
  // colSpan: 3 next to main_purpose at colSpan: 7 below (10/12, two
  // spare) — order in the `fields` array is what puts them in the same
  // row. Blocks default to colSpan: 12 (full width) when unset, since a
  // dropped-in component is more often a standalone widget than "just
  // another field."
  //
  // Extra keys on a customBlocks entry (valueKey, options, label below)
  // are passed straight through to the component as `field` — same
  // convention as any other field definition.
  customBlocks: [
    { key: 'main_purpose', component: MainPurposePills, colSpan: 7 },
    // Example: a company photo gallery, wired the exact same way — its
    // key just needs to appear in some section's `fields` array below.
    // { key: 'company_gallery', component: CompanyGallery },
  ],

  fieldGroups: [],

  sections: [
    { key: 'image_isle', label: '_', columns: 1, fields: ['company_logo'] },
    { key: 'basic_information', label: 'Basic Information', columns: 4, fields: ['company_name', 'main_purpose', 'phone_number', 'email',  'address'] },
    // Example: a full-width section at the end of the form for the
    // gallery block above — position is just where this section sits
    // in the array, same as everything else.
    // { key: 'gallery_section', label: 'Gallery', columns: 12, fields: ['company_gallery'] },
  ],

  fields: [
    // key: DB column name | label: shown on screen | type: drives input + SQL type
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'company_id', label: 'Company Id', type: 'text', system: true, editable: false },
    { key: 'company_name', label: 'Company Name', type: 'text', title: true, required: true, searchable: true, colSpan: 5 },
    { key: 'company_code', label: 'Company Code', type: 'text', title: true, searchable: true },
    { key: 'phone_number', label: 'Phone Number', type: 'text', searchable: true, colSpan: 5 },
    { key: 'email', label: 'Email', type: 'text', searchable: true, colSpan: 5 },
    { key: 'address', label: 'Address', type: 'textarea', colSpan: 12, searchable: true },
    { key: 'status', label: 'Status', type: 'groupedSelect', endpoint: '/api/assetguard/companies', groupByField: 'status', searchable: true },
    { key: 'reg_date', label: 'Reg Date', type: 'datetime' },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },
    { key: 'company_logo', label: 'Logo', type: 'image', searchable: false, imageClass: "useravatar_120" },
    // Backs the MainPurposePills customBlock above (comma-separated).
    // Deliberately NOT listed in any section's `fields` — the block
    // itself renders it, not FieldRenderer — but it still needs to be a
    // real field so FormEngine seeds it from an existing record on edit,
    // and route.js picks it up as a normal writable column.
    { key: 'purposes', label: 'Purposes', type: 'text', searchable: false },

    // more fields... see SCHEMA-SPEC.md for the full field option list
    // (searchable, editable, options, priority, db overrides)
  ],

  filters: [
    { key: 'all', label: 'All', query: {} },
  ],

  actions: [
    // { key: 'some_action', label: 'Do Something', appliesTo: { status: 'x' } },
    // "key" must match a function registered in lib/actionsRegistry.js
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    // "_staff_full_name_staff_id": {
    //   type: "join", table: "staff", link: "staff_id:record_id",
    //   select: { "_staff_full_name_staff_id": "full_name" }
    // },
  },

  // Optional: only needed if permission keys don't follow the
  // view_<entity> / manage_<entity> default.
  // roles: { view: 'view_companies', manage: 'manage_companies' },
};