// This is the ONLY file that changes when you clone this module.
// See SCHEMA-SPEC.md for the full reference — quick version below.
// Rough cut auto-generated by db-cli.js (rule-based column-name matching,
// no AI) — hand-tune sections/profileActions/groupedSelect below same as
// any other cloned module.

export const DevicesSchema = {
  entity: 'device_list',              // DB table name; also drives default role names
                                     // (view_devices / manage_devices) and apiBase
  label: 'Devices',                 // optional, defaults to entity capitalized
  apiBase: '/api/assetguard/devices',

  // Field keys shown as columns in list view, in display order.
  showInList: ['row_count', 'device_name', 'date_installed', 'serial_number', 'remark', 'registered_on', 'geofence', 'site_id'],

  rowLinks: [],

  profileActions: [
    { key: 'back', label: 'Back to list', icon: 'arrow-left', variant: 'outline-secondary', navigateTo: '/assetguard/devices/list' },
    { key: 'delete', label: 'Delete', icon: 'trash', variant: 'outline-danger', confirm: 'Are you sure you want to delete this device?', editOnly: true },
    { key: 'new', label: 'New Device', icon: 'plus', variant: 'outline-primary', navigateTo: '/assetguard/devices/profile' },
    //{ key: 'clone', label: 'Clone Record', icon: 'copy', variant: 'outline-secondary', editOnly: true },
    //{ key: 'filterByDate', label: 'Filter by date', icon: 'calendar', variant: 'outline-primary' },
  ],

  fieldGroups: [],

  sections: [
    { key: 'basic_information', label: 'Basic Information', columns: 3, fields: ['device_name', 'date_installed', 'serial_number', 'remark', 'registered_on', 'geofence', 'site_id'] },
    { key: 'other_details', label: 'Other Details', columns: 3, fields: ['site_name', 'low_battery_level', 'geofence_limit_distance', 'device_location', 'speed_alert_value', 'device_type', 'status', 'last_seen', 'hive_site_id', 'hive_site_name'] },
  ],

  fields: [
    // key: DB column name | label: shown on screen | type: drives input + SQL type
    { key: 'primkey', label: 'Primkey', type: 'number', system: true, editable: false },
    { key: 'record_id', label: 'Record Id', type: 'text', system: true, editable: false },
    { key: 'device_name', label: 'Device Name', type: 'text', title: true, required: true, searchable: true },
    { key: 'date_installed', label: 'Date Installed', type: 'datetime' },
    { key: 'serial_number', label: 'Serial Number', type: 'text', searchable: true },
    { key: 'remark', label: 'Remark', type: 'textarea', colSpan: 3, searchable: true },
    { key: 'registered_on', label: 'Registered On', type: 'datetime' },
    { key: 'geofence', label: 'Geofence', type: 'text', searchable: true },
    { key: 'site_id', label: 'Site Id', type: 'text', searchable: true },
    { key: 'site_name', label: 'Site Name', type: 'text', title: true, searchable: true },
    { key: 'low_battery_level', label: 'Low Battery Level', type: 'text', searchable: true },
    { key: 'geofence_limit_distance', label: 'Geofence Limit Distance', type: 'text', searchable: true },
    { key: 'device_location', label: 'Device Location', type: 'text', searchable: true },
    { key: 'speed_alert_value', label: 'Speed Alert Value', type: 'text', searchable: true },
    { key: 'device_type', label: 'Device Type', type: 'text', searchable: true },
    { key: 'status', label: 'Status', type: 'groupedSelect', endpoint: '/api/assetguard/devices', groupByField: 'status', searchable: true },
    { key: 'last_seen', label: 'Last Seen', type: 'datetime' },
    { key: 'hive_site_id', label: 'Hive Site Id', type: 'text', searchable: true },
    { key: 'hive_site_name', label: 'Hive Site Name', type: 'text', title: true, searchable: true },
    { key: 'row_count', label: '#', type: 'number', computed: true, editable: false },
    // more fields... see SCHEMA-SPEC.md for the full field option list
    // (searchable, editable, options, priority, db overrides)
  ],

  filters: [
    { key: 'all', label: 'All', query: {} },
  ],

  actions: [
    // { key: 'some_action', label: 'Do Something', appliesTo: { status: 'x' } },
    // "key" must match a function registered in lib/actionsRegistry.js
  ],

  // Optional: joins enriching each row with data from another table.
  // Same shape as your existing *BatchMutations.js files.
  batchMutations: {
    // "_staff_full_name_staff_id": {
    //   type: "join", table: "staff", link: "staff_id:record_id",
    //   select: { "_staff_full_name_staff_id": "full_name" }
    // },
  },

  // Optional: only needed if permission keys don't follow the
  // view_<entity> / manage_<entity> default.
  // roles: { view: 'view_devices', manage: 'manage_devices' },
};
